# Required: Home Assistant integration (MQTT discovery) (default: false)
homeassistant: false

# Required: allow new devices to join.
# WARNING: Disable this after all devices have been paired! (default: false)
permit_join: true

# Required: MQTT settings
mqtt:
  # Required: MQTT base topic for zigbee2mqtt MQTT messages
  base_topic: zigbee2mqtt
  # Required: MQTT server URL (use mqtts:// for SSL/TLS connection)
  server: "mqtt://localhost:1883"
  # Optional: absolute path to SSL/TLS certificate of CA used to sign server and client certificates (default: nothing)
  user: my_user
  # Optional: MQTT server authentication password (default: nothing)
  password: my_password
  # Optional: MQTT keepalive in seconds (default: 60)
  keepalive: 60

# Required: serial settings
serial:
  # Required: location of the adapter (e.g. CC2531).
  # To autodetect the port, set 'port: null'.
  port: /dev/ttyACM0
  # Optional: disable LED of the adapter if supported (default: false)
  disable_led: false

# Optional: advanced settings
advanced:
  # Optional: Location of log directory (default: shown below)
  log_directory: data/log/
  # Optional: Log file name, can also contain timestamp, e.g.: zigbee2mqtt_%TIMESTAMP%.log (default: shown below)
  log_file: zigbee2mqtt_%TIMESTAMP%.log
  # Optional: Output location of the log (default: shown below), leave empty to supress logging (log_output: [])
  log_output:
    - console
    - file

# Optional: experimental options
experimental:
  # Optional: MQTT output type: json, attribute or json_and_attribute (default: shown below)
  # Examples when 'state' of a device is published
  # json: topic: 'zigbee2mqtt/my_bulb' payload '{"state": "ON"}'
  # attribute: topic 'zigbee2mqtt/my_bulb/state' payload 'ON"
  # json_and_attribute: both json and attribute (see above)
  output: "json"

devices: devices.yaml
groups: groups.yaml
