name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  download_loxberry:
    runs-on: ubuntu-latest
    steps:
      - name: install deps
        run: sudo apt-get update && sudo apt-get install -y wget p7zip-full sshpass
      - name: dl image
        run: wget -nv https://loxberry.kim.bz/stable/images/rasppi/loxberry-image-rasppi-2.0.0_bilbo.img.7z
      - name: unpack
        run: 7z x loxberry-image-rasppi-2.0.0_bilbo.img.7z
      - name: run image
        run: docker run -d --name loxberry --rm -v $PWD/loxberry-image-rasppi-2.0.0_bilbo.img:/sdcard/filesystem.img --health-cmd "netstat -lntp |grep 5022" --health-interval 10s --health-timeout 5m --health-retries 10 -p 5022:5022 lukechilds/dockerpi:vm
      - name: dl wait script
        run: wget -nv https://raw.githubusercontent.com/jordyv/wait-for-healthy-container/master/wait-for-healthy-container.sh
      - name: change exec priv
        run: chmod +x wait-for-healthy-container.sh     
      - name: wait for docker
        run: ./wait-for-healthy-container.sh loxberry 300
      - name: run script
        run: sshpass -p loxberry ssh loxberry@localhost -p 5022 ls
      - name: delete container
        run: docker rm -f loxberry
        
