name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: node:10.18-jessie

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      loxberry:
        # Docker Hub image
        image: lukechilds/dockerpi
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "systemctl is-active --quiet sshd"
          --health-interval 10s
          --health-timeout 5m
          --health-retries 10

    steps:
      - name: Install dependencies
        run: echo "hallo"
