name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: lukechilds/dockerpi
    steps:
      - name: Run entrypoint
        run: /entrypoint.sh 
